export {default as Footer}  from './Footer'
export {default as Navbar}  from './Navbar'
export {default as Slider}  from './Slider'
export {default as  Card}  from './Card'
export {default as  Categories}  from './Categories'
export {default as  FeaturedProducts}  from './FeaturedProducts'
export {default as  List}  from './List'
